# Generated by Django 4.1 on 2022-10-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="input_type",
            field=models.CharField(choices=[("STATIC", "Static"), ("LIVE", "Live")], default="LIVE", max_length=10),
        ),
        migrations.AddField(
            model_name="input",
            name="s3_url",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="input",
            name="port",
            field=models.IntegerField(
                default=0, help_text="If no port specified, the Default port for protocol will be used"
            ),
        ),
    ]
