# Generated by Django 4.1 on 2022-11-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_input_input_type_input_s3_url_alter_input_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="schedule",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.schedule"),
        ),
    ]
