# Generated by Django 4.0 on 2022-11-13 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_input_input_type_input_s3_url_alter_input_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playout_id', models.UUIDField()),
                ('callback_endpoint', models.URLField()),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('exception', models.TextField()),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('sig_timestamp', models.CharField(blank=True, max_length=10, null=True)),
                ('sig_body', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_callback_log',
            },
        ),
        migrations.CreateModel(
            name='CallbackSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('retry_count', models.IntegerField(default=3)),
                ('signing_secret', models.CharField(default='', max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_callback_subscriber',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='aws_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='api.schedule'),
        ),
        migrations.CreateModel(
            name='CallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('playout.created', 'playout.created'), ('input.created', 'input.created'), ('channel.running', 'channel.running'), ('channel.stopped', 'channel.stopped'), ('clipping.success', 'clipping.success'), ('clipping.failed', 'clipping.failed')], max_length=50)),
                ('object_id', models.CharField(default='', max_length=128)),
                ('event_object', models.TextField()),
                ('retried_count', models.IntegerField(default=0)),
                ('delivered_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('playout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='api.playout')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='api.callbacksubscriber')),
            ],
            options={
                'db_table': 'api_callback_event',
            },
        ),
    ]
