# Generated by Django 4.1 on 2022-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_callbacklog_callbacksubscriber_channel_aws_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="aws_flow_arn",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
