# Generated by Django 4.1 on 2022-11-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_channel_schedule"),
        ("api", "0004_input_aws_flow_arn"),
    ]

    operations = []
