# Generated by Django 4.1 on 2022-11-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20221121_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="loop",
            field=models.CharField(
                choices=[("CONTINUE", "Continue"), ("LOOP", "Loop")], default="CONTINUE", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="schedule",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="channels", to="api.schedule"
            ),
        ),
    ]
