# Generated by Django 4.1 on 2022-11-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_clip_vod_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="vod",
            name="clip",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.clip"
            ),
        ),
        migrations.AddField(
            model_name="vod",
            name="clip_hls_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="vod",
            name="create_type",
            field=models.CharField(
                blank=True,
                choices=[("media_convert", "media_convert"), ("harvest_job", "harvest_job")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vod",
            name="input_video_s3_object_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="vodasset",
            name="vod",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.vod"
            ),
        ),
        migrations.AlterField(
            model_name="vod",
            name="original_video",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.rawvideo"
            ),
        ),
    ]
