# Generated by Django 4.1 on 2022-12-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_vod_clip_vod_clip_hls_path_vod_create_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="preview_channel_id",
            field=models.UUIDField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="preview_mp_channel_id",
            field=models.UUIDField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="preview_origin_endpoint_id",
            field=models.UUIDField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="preview_origin_id",
            field=models.UUIDField(auto_created=True, null=True),
        ),
    ]
