# Generated by Django 4.1 on 2022-12-09 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_input_preview_channel_id_input_preview_mp_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="preview_channel_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="input",
            name="preview_mp_channel_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="input",
            name="preview_origin_endpoint_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="input",
            name="preview_origin_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
