version: '2'

volumes:
    postgres_data: {}

services:
  backend:
    build:
      context: ./apps/veepsapi/
    depends_on:
      - postgres
    volumes:
      - ./apps/veepsapi:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env
    ports:
      - "8000:8000"
  postgres:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
