def get_dashboard_body(channel_name, channel_id, region, mediapackage_channel_uuid, channel_hls_url):
    body = {
        "widgets": [
            {
                "height": 1,
                "width": 24,
                "y": 0,
                "x": 0,
                "type": "text",
                "properties": {"markdown": f"# {channel_name}\n: Encoding"},
            },
            {"height": 1, "width": 12, "y": 1, "x": 0, "type": "text", "properties": {"markdown": "## Input"}},
            {
                "height": 9,
                "width": 12,
                "y": 2,
                "x": 0,
                "type": "metric",
                "properties": {
                    "annotations": {
                        "horizontal": [
                            {"label": "30 frames per second", "value": 30},
                            {"label": "30 frames per second", "value": 30, "yAxis": "right"},
                            {"label": "60 frames per second", "value": 60},
                            {"label": "60 frames per second", "value": 60, "yAxis": "right"},
                        ]
                    },
                    "metrics": [
                        [
                            "MediaLive",
                            "InputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "InputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Average",
                    "title": "Input Video Frame Rate (avg)",
                    "view": "timeSeries",
                    "yAxis": {"left": {"min": 0}, "right": {"min": 0}},
                },
            },
            {
                "height": 9,
                "width": 12,
                "y": 11,
                "x": 0,
                "type": "metric",
                "properties": {
                    "metrics": [
                        [
                            "MediaLive",
                            "NetworkIn",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "NetworkIn",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Sum",
                    "title": "Network In (sum)",
                    "view": "timeSeries",
                    "yAxis": {"left": {"min": 0}, "right": {"min": 0}},
                },
            },
            {
                "height": 6,
                "width": 12,
                "y": 20,
                "x": 0,
                "type": "metric",
                "properties": {
                    "legend": {"position": "bottom"},
                    "metrics": [
                        [
                            "MediaLive",
                            "DroppedFrames",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "DroppedFrames",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Sum",
                    "title": "Dropped Frames (sum)",
                    "view": "timeSeries",
                    "yAxis": {"left": {"min": 0}, "right": {"min": 0}},
                },
            },
            {
                "height": 6,
                "width": 12,
                "y": 26,
                "x": 0,
                "type": "metric",
                "properties": {
                    "legend": {"position": "bottom"},
                    "metrics": [
                        [
                            "MediaLive",
                            "FillMsec",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "FillMsec",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Sum",
                    "title": "Fill Milliseconds (sum)",
                    "view": "timeSeries",
                },
            },
            {
                "height": 6,
                "width": 12,
                "y": 32,
                "x": 0,
                "type": "metric",
                "properties": {
                    "legend": {"position": "bottom"},
                    "metrics": [
                        [
                            "MediaLive",
                            "SvqTime",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "SvqTime",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 300,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Average",
                    "title": "SVQ Time (percentage)",
                    "view": "timeSeries",
                },
            },
            {"height": 1, "width": 12, "y": 1, "x": 12, "type": "text", "properties": {"markdown": "## Output"}},
            {
                "height": 9,
                "width": 12,
                "y": 2,
                "x": 12,
                "type": "metric",
                "properties": {
                    "annotations": {
                        "horizontal": [
                            {"label": "30 frames per second", "value": 30},
                            {"label": "30 frames per second", "value": 30, "yAxis": "right"},
                            {"label": "60 frames per second", "value": 60},
                            {"label": "60 frames per second", "value": 60, "yAxis": "right"},
                        ]
                    },
                    "metrics": [
                        [
                            "MediaLive",
                            "OutputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "OutputName",
                            "1080p30",
                            "Pipeline",
                            "0",
                        ],
                        [
                            "MediaLive",
                            "OutputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "OutputName",
                            "720p30",
                            "Pipeline",
                            "0",
                        ],
                        [
                            "MediaLive",
                            "OutputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "OutputName",
                            "480p30",
                            "Pipeline",
                            "0",
                        ],
                        [
                            "MediaLive",
                            "OutputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "OutputName",
                            "240p30",
                            "Pipeline",
                            "0",
                        ],
                        [
                            "MediaLive",
                            "OutputVideoFrameRate",
                            "ChannelId",
                            f"{channel_id}",
                            "OutputName",
                            "mediastore1080p30",
                            "Pipeline",
                            "0",
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Average",
                    "title": "Output Video Frame Rate (avg)",
                    "view": "timeSeries",
                    "yAxis": {"left": {"min": 0}, "right": {"min": 0}},
                },
            },
            {
                "height": 9,
                "width": 12,
                "y": 11,
                "x": 12,
                "type": "metric",
                "properties": {
                    "metrics": [
                        [
                            "MediaLive",
                            "NetworkOut",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "NetworkOut",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": False,
                    "stat": "Sum",
                    "title": "Network Out (sum)",
                    "view": "timeSeries",
                    "yAxis": {"left": {"min": 0}, "right": {"min": 0}},
                },
            },
            {
                "height": 12,
                "width": 12,
                "y": 20,
                "x": 12,
                "type": "metric",
                "properties": {
                    "metrics": [
                        [
                            "MediaLive",
                            "ActiveOutputs",
                            "OutputGroupName",
                            "HD",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "ActiveOutputs",
                            "OutputGroupName",
                            "HD",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                        [
                            "MediaLive",
                            "ActiveOutputs",
                            "OutputGroupName",
                            "MediaStore",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "0",
                            {"label": f"{channel_name}-0"},
                        ],
                        [
                            "MediaLive",
                            "ActiveOutputs",
                            "OutputGroupName",
                            "MediaStore",
                            "ChannelId",
                            f"{channel_id}",
                            "Pipeline",
                            "1",
                            {"label": f"{channel_name}-1", "yAxis": "right"},
                        ],
                    ],
                    "period": 60,
                    "region": f"{region}",
                    "stacked": True,
                    "stat": "Average",
                    "title": "Active Output Renditions (avg)",
                    "view": "timeSeries",
                    "yAxis": {"left": {"min": 0}},
                },
            },
            {
                "height": 6,
                "width": 12,
                "y": 32,
                "x": 12,
                "type": "text",
                "properties": {
                    "markdown": f"""# Console Links for all channels
                        Hold down the Control (Ctrl) key when selecting a link 
                        to open the console in a new tab within the browser.   

                        MediaLive: [{channel_name} - {channel_id}](https://{region}.console.aws.amazon.com/medialive/home?region={region}#/channels/{channel_id}) 
                        MediaPackage:   https://{region}.console.aws.amazon.com/mediapackage/home?region={region}#/channels/{mediapackage_channel_uuid}tabId=ingestEgress
                        HLS Output: {channel_hls_url}
                        """
                },
            },
        ]
    }

    return body
