# Generated by Django 4.1 on 2022-11-03 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_channel_schedule"),
        ("users", "0001_inital"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_addr", models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name="ShowRunner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "playout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="showrunner", to="api.playout"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showrunner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
