# Generated by Django 4.1 on 2022-11-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_vod_clip_vod_clip_hls_path_vod_create_type_and_more"),
        ("users", "0002_allowlist_showrunner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showrunner",
            name="playout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="showrunners", to="api.playout"
            ),
        ),
    ]
